knn_scenario:
  model_class: "sklearn.neighbors.KNeighborsClassifier"
  model_name: "KNN"
  hyperparameters:
    n_neighbors:
      type: "int"
      low: 3
      high: 15
    weights:
      type: "categorical"
      choices: ["uniform", "distance"]

decision_tree_scenario:
  model_class: "sklearn.tree.DecisionTreeClassifier"
  model_name: "DecisionTree"
  hyperparameters:
    max_depth:
      type: "int"
      low: 2
      high: 10
    criterion:
      type: "categorical"
      choices: ["gini", "entropy"]