knn_scenario:
  model_class: "sklearn.neighbors.KNeighborsClassifier"
  hyperparameters:
    n_neighbors:
      type: "int"
      low: 
      high: 
    weights:
      type: ""
      choices: []

decision_tree_scenario:
  model_class: "sklearn.tree.DecisionTreeClassifier"
  hyperparameters:
    max_depth:
      type: ""
      low: 
      high: 
    criterion:
      type: ""
      choices: []

random_forest_scenario:
  model_class: "sklearn.ensemble.RandomForestClassifier"
  hyperparameters:
    n_estimators:
      type: ""
      low: 
      high: 
    max_depth:
      type: ""
      low: 
      high: 

svm_scenario:
  model_class: "sklearn.svm.SVC"
  hyperparameters:
    C:
      type: ""
      low: 
      high: 
      log: 
    kernel:
      type: ""
      choices: []